kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-cluster
networking:
  ipFamily: ipv6
nodes:
- role: control-plane
  image: kindest/node:v1.22.5
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
